server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: restaurant-service

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_db
    username: restaurant_db
    password: restaurant_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  images:
    upload-dir: ./images
    base-url: /images
    allowed-formats: jpg,jpeg,png,gif,webp
    max-size-mb: 5

jwt:
  secret: "mysecretkeymysecretkeymysecretkeymysecretkeymysecretkeymysecretkey"
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.example.restaurantservice: DEBUG
    org.springframework.security: DEBUG