server:
  port: 8082

spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:postgresql://postgres:5432/restaurant_db
    username: restaurant_db
    password: restaurant_db
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: restaurant-service
    prefer-ip-address: false

jwt:
  secret: "mysecretkey"